base/urls.py
from django.urls import path
from .views import (
    home,
    room,
    createroom,
    updateroom,
    deleteroom,
    loginpage,
    logoutuser,
    registeruser,
    deletemessage,
    userprofile,
    updateuser,
    topicspage,
    activitypage,
)

app_name = 'base'

urlpatterns = [
    path('login/', loginpage, name='login'),
    path('logout/', logoutuser, name='logout'),
    path('register', registeruser, name='register'),

    path('', home, name='home'),
    path('room/<int:id>/', room, name='room'),
    path('profile/<int:id>/', userprofile, name='userprofile'),

    path('create-room/', createroom, name='create-room'),
    path('update-room/<int:id>', updateroom, name='update-room'),
    path('delete-room/<int:id>', deleteroom, name='delete-room'),
    path('delete-message/<int:id>', deletemessage, name='delete-message'),

    path('update-user/', updateuser, name='update-user'),

    path('topics/', topicspage, name='topics'),
    path('activity/', activitypage, name='activity'),
]

studybud/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True, default="avatar.svg")
    
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from .models import Room, User
from django.contrib.auth.forms import UserCreationForm
from django import forms


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']


class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']

base/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from .models import Room, Topic, Message, User
from .forms import RoomForm, RegisterForm, UserForm, MyUserCreationForm
from django.contrib.auth import authenticate, login, logout


# Create your views here.
# rooms = [
#     {'id': 1, 'name': 'lets learn python!'},
#     {'id': 2, 'name': 'Design with me'},
#     {'id': 3, 'name': 'Frontend developers'},
# ]

def loginpage(request):
    page = 'login'
    if request.user.is_authenticated:
        return redirect('base:home')

    if request.method == 'POST':
        email = request.POST.get('email').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(email=email)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('base:home')
        else:
            messages.error(request, 'Username or Password does not exist ')

    context = {'page': page}
    return render(request, 'base/login_register.html', context)


def registeruser(request):
    form = MyUserCreationForm()
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            return redirect('login/')
        else:
            messages.error(request, 'An error occurred during registration')
    else:
        form = MyUserCreationForm()
    return render(request, 'base/login_register.html', {'form': form})


def logoutuser(request):
    logout(request)
    return redirect('base:login')


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q)
    )
    topics = Topic.objects.all()[0:5]
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    context = {
        'rooms': rooms,
        'topics': topics,
        'room_count': room_count,
        'room_messages': room_messages,

    }
    return render(request, 'base/home.html', context)


def room(request, id):
    room = Room.objects.get(id=id)
    room_messages = room.message_set.all()
    participants = room.participants.all()

    if request.method == "POST":
        if request.POST.get('body'):
            message = request.POST.get('body')
            room.message_set.create(
                user=request.user,
                body=message,

            )
            room.participants.add(request.user)
            return redirect('base:room', id=room.id)
    context = {
        'room': room,
        'room_messages': room_messages,
        'participants': participants
    }
    return render(request, 'base/room.html', context)


def userprofile(request, id):
    user = User.objects.get(id=id)
    rooms = user.room_set.all()
    room_messages = user.message_set.all()
    topics = Topic.objects.all()
    context = {'user': user, 'rooms': rooms,
               'room_messages': room_messages,
               'topics': topics,
               }
    return render(request, 'base/profile.html', context)


@login_required(login_url='base:login')
def createroom(request):
    form = RoomForm()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get("topic")
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host=request.user,
            topic=topic,
            name=request.POST.get('name'),
            description=request.POST.get('description'),
        )
        return redirect('base:home')
    context = {
        'form': form,
        'topics': topics
    }
    return render(request, 'base/room_form.html', context)


@login_required(login_url='base:login')
def updateroom(request, id):
    room = Room.objects.get(id=id)
    form = RoomForm(request.POST or None, instance=room)
    topics = Topic.objects.all()
    if request.user != room.host:
        return HttpResponse("you're not allowed here")
    if request.method == 'POST':
        topic_name = request.POST.get("topic")
        topic, created = Topic.objects.get_or_create(name=topic_name)
        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('base:home')

    context = {
        'form': form,
        'topics': topics,
        'room': room
    }

    return render(request, 'base/room_form.html', context)


@login_required(login_url='base:login')
def deleteroom(request, id):
    room = Room.objects.get(id=id)
    if request.user != room.host:
        return HttpResponse("you're not allowed here")
    if request.method == 'POST':
        room.delete()
        return redirect('base:home')
    return render(request, 'base/delete.html', {'obj': room})


@login_required(login_url='base:login')
def deletemessage(request, id):
    message = Message.objects.get(id=id)

    if request.user != message.user:
        return HttpResponse("you're not allowed here")

    if request.method == 'POST':
        message.delete()
        return redirect('base:home')
    return render(request, 'base/delete.html', {'obj': message})


@login_required(login_url='base:login')
def updateuser(request):
    user = request.user
    form = UserForm(instance=user)
    if request.method == "POST":
        form = UserForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('base:userprofile', id=user.id)
    context = {'form': form}
    return render(request, 'base/update-user.html', context)


def topicspage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    topics = Topic.objects.filter(name__icontains=q)
    return render(request, 'base/topics.html', {'topics': topics})


def activitypage(request):
    room_messages = Message.objects.all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})

base/templates/base/activity_component.html
 <div class="activities">
          <div class="activities__header">
            <h2>Recent Activities</h2>
          </div>
          {% for message in room_messages %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
              <a href="{% url 'base:userprofile' message.user.id  %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                  {{message.user}}
                  <span>{{message.created|timesince}} ago</span>
                </p>
              </a>
                {% if  request.user == message.user %}
              <div class="roomListRoom__actions">
                <a href="{% url 'base:delete-message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
                {% endif %}
            </div>
            <div class="activities__boxContent">
              <p>replied to post “<a href="{% url 'base:room' message.room.id %}">{{ message.room}}</a></p>
              <div class="activities__boxRoomContent">
                {{ message.body }}
              </div>
            </div>
          </div>
         {% endfor %}

        </div>

base/templates/base/delete.html
{% extends 'main.html' %}
{% block content %}
    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{obj}}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="script.js"></script>
{% endblock %}

base/templates/base/delete_old.html
{% extends 'main.html' %}


{% block content %}
<form method="POST" action="">
    {% csrf_token %}
    <p>Are you sure you want to delete '{{obj.name}}'?</p>
    <a href="{{ request.META.HTTP_REFERER }}">Go Back</a>
    <input type="submit" value="Confirm">
</form>

{% endblock %}

base/templates/base/feed_component.old.html
<div>
        {% for room in rooms %}
            <div>
                {% if request.user == room.host %}
                <a href="{% url 'base:update-room' room.id %}">Edit</a>
                <a href="{% url 'base:delete-room' room.id %}">Delete</a>
                {% endif %}
                <a href="{% url 'base:userprofile' room.host.id %}">@{{room.host.username}}</a>
                <h5>{{ room.id }} -- <a href="{% url 'base:room' room.id %}">{{ room.name}}</a></h5>
                <small>{{room.topic.name}}</small>
                <hr>

            </div>
        {% endfor %}
    </div>

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'base/topics_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'base:home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'base:topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'base:activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms</h2>
          <p>{{room_count}} Rooms available</p>
        </div>

        <a class="btn btn--main" href="{% url 'base:create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Create Room
        </a>
      </div>

      {% include 'base/feed_component.html' %}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

base/templates/base/login_register_old.html
{% extends 'main.html' %}

{% block content %}
{% if page == 'login' %}
<div>
    <form method="post" action = "">
        {% csrf_token %}
        <label>Username:</label>
        <input type="text" name="username" placeholder="Enter Username"/>

        <label>Password</label>
        <input type="password" name="password" placeholder="Enter password">

        <input type="submit" value="Login">

        <p> Haven't signed up yet? <a href="{% url 'base:register' %}">Sign up</a> </p>

    </form>
</div>

{% else %}

<div>
    <form method="post" action = "">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Register">
    </form>
     <p> Already signed up ? <a href="{% url 'base:login' %}">Login</a> </p>

</div>
{% endif %}

{% endblock %}

base/templates/base/profile.html
{% extends 'main.html' %}
{% block content %}
  <main class="profile-page layout layout--3">
    <div class="container">
      <!-- Topics Start -->
       {% include 'base/topics_component.html' %}
      <!-- Topics End -->

      <!-- Room List Start -->
      <div class="roomList">
        <div class="profile">
          <div class="profile__avatar">
            <div class="avatar avatar--large active">
              <img src="https://randomuser.me/api/portraits/men/11.jpg" />
            </div>
          </div>
          <div class="profile__info">
            <h3>{{ user.username}}</h3>
            <p>{{ user.username}}</p>
            {% if request.user == user %}
            <a href="{% url 'base:update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
            {% endif %}
          </div>
          <div class="profile__about">
            <h3>About</h3>
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo tenetur
              facilis sunt nemo debitis quisquam hic atque aut? Ducimus alias placeat optio
              accusamus repudiandae quis ab ex exercitationem rem?
            </p>
          </div>
        </div>

        <div class="roomList__header">
          <div>
            <h2>Study Rooms Hosted by dennis_ivy</a>
            </h2>
          </div>
        </div>
         {% include 'base/feed_component.html' %}
      </div>
      <!-- Room List End -->

      <!-- Activities Start -->
      {% include 'base/activity_component.html' %}
      <!-- Activities End -->
    </div>
  </main>
{% endblock %}

base/templates/base/profile_old.html
{% extends 'main.html' %}

{% block content %}

<style>
    .profile-container{
            display: grid;
            grid-template-columns: 1fr 3fr 1fr;

    }
</style>
<h1>{{user.username}}</h1>
        <hr>
<div class="profile-container" >
    <div>
        {% include 'base/topics_component.html' %}
    </div>

    <div>
        {% include 'base/feed_component.html' %}
    </div>

    <div>
        {% include 'base/activity_component.html' %}

    </div>
</div>


{% endblock %}

base/templates/base/room.html
{% extends 'main.html' %}
{% block content %}
<main class="profile-page layout layout--2">
   <div class="container">
        <!-- Room Start -->
     <div class="room">
          <div class="room__top">
            <div class="room__topLeft">
              <a href="{% url 'base:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                  </path>
                </svg>
              </a>
              <h3>Study Room</h3>
            </div>

            {% if room.host == request.user %}
            <div class="room__topRight">
              <a href="{% url 'base:update-room' room.id %}">
                <svg
                  enable-background="new 0 0 24 24" height="32" viewBox="0 0 24 24" width="32"
                  xmlns="http://www.w3.org/2000/svg">
                  <title>edit</title>
                  <g>
                    <path d="m23.5 22h-15c-.276 0-.5-.224-.5-.5s.224-.5.5-.5h15c.276 0 .5.224.5.5s-.224.5-.5.5z" />
                  </g>
                  <g>
                    <g>
                      <path
                        d="m2.5 22c-.131 0-.259-.052-.354-.146-.123-.123-.173-.3-.133-.468l1.09-4.625c.021-.09.067-.173.133-.239l14.143-14.143c.565-.566 1.554-.566 2.121 0l2.121 2.121c.283.283.439.66.439 1.061s-.156.778-.439 1.061l-14.142 14.141c-.065.066-.148.112-.239.133l-4.625 1.09c-.038.01-.077.014-.115.014zm1.544-4.873-.872 3.7 3.7-.872 14.042-14.041c.095-.095.146-.22.146-.354 0-.133-.052-.259-.146-.354l-2.121-2.121c-.19-.189-.518-.189-.707 0zm3.081 3.283h.01z"/>
                    </g>
                    <g>
                      <path
                        d="m17.889 10.146c-.128 0-.256-.049-.354-.146l-3.535-3.536c-.195-.195-.195-.512 0-.707s.512-.195.707 0l3.536 3.536c.195.195.195.512 0 .707-.098.098-.226.146-.354.146z"/>
                    </g>
                  </g>
                </svg>
              </a>
              <a href="{% url 'base:delete-room' room.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"></path>
                </svg>
              </a>
            </div>
            {% endif %}

          </div>
          <div class="room__box scroll">
            <div class="room__header scroll">
              <div class="room__info">
                <h3>{{ room.name }}</h3>
                <span>{{room.created|timesince}}</span>
              </div>
              <div class="room__hosted">
                <p>Hosted By</p>
                <a href="{% url 'base:userprofile' room.host.id %}" class="room__author">
                  <div class="avatar avatar--small">
                    <img src="{{room.host.avatar.url}}" />
                  </div>
                  <span>@{{room.host.username}}</span>
                </a>
              </div>

              <span class="room__topics">{{ room.topic }}</span>
            </div>
            <div class="room__conversation">
              <div class="threads scroll">
                {% for message in  room_messages %}
                <div class="thread">
                  <div class="thread__top">
                    <div class="thread__author">
                      <a href="{% url 'base:userprofile' message.user.id%}" class="thread__authorInfo">
                        <div class="avatar avatar--small">
                          <img src="{{message.user.avatar.url}}" />
                        </div>
                        <span>@{{message.user.username}}</span>
                      </a>
                      <span class="thread__date">{{message.created|timesince}}</span>
                    </div>

                    {% if message.user == request.user %}
                    <a href="{% url 'base:delete-message' message.id%}">
                      <div class="thread__delete">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                          <title>remove</title>
                          <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                          </path>
                        </svg>
                      </div>
                    </a>
                    {% endif %}
                  </div>
                  <div class="thread__details">
                    {{message.body}}
                </div>
              </div>
              {% endfor %}
            </div>
          </div>

        </div>
         <div class="room__message">
        <form action="" method="POST">
          {% csrf_token %}
          <input name="body" placeholder="Write your message here..." />
        </form>
      </div>
    </div>
        <!-- Room End -->

        <!--   Start -->
        <div class="participants">
          <h3 class="participants__top">Participants <span>({{participants.count }} Joined)</span></h3>
          <div class="participants__list scroll">
            {% for user in participants %}
            <a href="{% url 'base:userprofile' user.id %}" class="participant">
              <div class="avatar avatar--medium">
                <img src="https://randomuser.me/api/portraits/men/37.jpg" />
              </div>
              <p>
                  {{user.username}}
                <span>@{{ user.username }}</span>
              </p>
            </a>
            {% endfor %}
          </div>
        </div>
        <!--  End -->

   </div>

</main>
    <script src="script.js"></script>
{% endblock %}

base/templates/base/room_form._old.html
{% extends 'main.html' %}

{% block content %}
<div>
    <form method="POST" action="" >
        {% csrf_token %}
        {{ form.as_p }}

        <input type = 'submit' value="submit"/>

    </form>
</div>

{% endblock %}

base/templates/base/topics.html
{% extends 'main.html' %}
{% block content %}
    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'base:home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form action="" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name ="q" placeholder="Search for topics" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'base:topics' %}" class="active">All <span>{{topics.count}}</span></a>
              </li>
              {% for topic in topics %}
              <li>
                <a href="{% url 'base:home'%}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.all.count}}</span></a>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </main>
{% endblock %}

base/templates/base/topics_component.html
<div class="topics">
          <div class="topics__header">
            <h2>Browse Topics</h2>
          </div>
          <ul class="topics__list">
            <li>
              <a href="{% url 'base:home' %}" class="active">All <span>{{topics.count}}</span></a>
            </li>
               {% for topic in topics%}
            <li>
              <a href="{% url 'base:home' %}?q={{ topic.name}}">{{ topic.name }} <span>{{topic.room_set.all.count}}</span></a>
            </li>
              {% endfor %}

          </ul>
          <a class="btn btn--link" href="{% url 'base:topics' %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </div>

base/templates/base/topics_component_old.html
<h3>Browse Topics</h3>
        <hr>

        <div>
            <a href="{% url 'base:home' %}">All</a>
        </div>
            {% for topic in topics%}

            <div>
                <a href="{% url 'base:home' %}?q={{ topic.name}}">{{ topic.name }}</a>

            </div>
            {% endfor %}